@echo off
echo Fixing ChatSession userId field...

echo Adding userId to ChatWidget.tsx...
powershell -Command "(Get-Content 'src/components/features/chat/ChatWidget.tsx') -replace 'title: ''Cuộc trò chuyện mới'',', 'title: ''Cuộc trò chuyện mới'',`n        userId: user.uid || '''','" | Set-Content 'src/components/features/chat/ChatWidget.tsx'

echo Adding userId to useChat.ts...
powershell -Command "(Get-Content 'src/hooks/useChat.ts') -replace 'title: ''Cuộc trò chuyện mới'',', 'title: ''Cuộc trò chuyện mới'',`n        userId: user.uid || '''','" | Set-Content 'src/hooks/useChat.ts'

echo Adding eslint-disable comments...
powershell -Command "(Get-Content 'src/components/features/chat/ChatWidget.tsx') -replace '  }, \[user\?\.\accessToken\]\);$', '    // eslint-disable-next-line react-hooks/exhaustive-deps`n  }, [user?.accessToken]);'" | Set-Content 'src/components/features/chat/ChatWidget.tsx'

powershell -Command "(Get-Content 'src/hooks/useChat.ts') -replace '  }, \[user\?\.\accessToken\]\);$', '    // eslint-disable-next-line react-hooks/exhaustive-deps`n  }, [user?.accessToken]);'" | Set-Content 'src/hooks/useChat.ts'

echo Done! Running build test...
npm run build